# Use postgres/example user/password credentials
version: '3.1'
services:
  web:
    build: .
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
        - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.vaultwarden.entrypoints=web,websecure"
      - "traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=lets-encrypt"
    env_file:
      - .env.production

networks:
    web:
        external: true