# Use postgres/example user/password credentials
version: '3.1'
services:
  web:
    build: .
    networks:
        - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.preprodgcc.entrypoints=web,websecure"
      - "traefik.http.routers.preprodgcc.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.preprodgcc.loadbalancer.server.port=8000"
      - "traefik.http.routers.preprodgcc.tls=true"
      - "traefik.http.routers.preprodgcc.tls.certresolver=lets-encrypt"
    env_file:
      - .env
    volumes:
      - "./write-ups:/app/write-ups"
networks:
    web:
        external: true