# Use postgres/example user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - "27017:27017"

#  web:
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mongo